# Use postgres/example user/password credentials
version: '3'

services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    # volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    volumes:
      - onstudy-pgsqldata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: onstudy
    ports:
      - 5432:5432
    networks:
      onstudy_backend:
        ipv4_address: 172.20.0.2

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    volumes:
      - onstudy-pgadmindata:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@root.com
      - PGADMIN_DEFAULT_PASSWORD=pwd
    networks:
      onstudy_backend:
        ipv4_address: 172.20.0.3

networks:
  onstudy_backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  onstudy-pgsqldata:
  onstudy-pgadmindata:
